version: '3.6'
services:
    act:
        build:
            context: "."
            dockerfile: "Dockerfile"
        depends_on:
            - "database"
        networks:
            - "default"
        ports:
            - "5000:5000"
        expose:
            - "5000"
        user: "root"
        command:
          - "plackup"
          - "-r"
          - "app.psgi"
        environment:
          - "ACT_HOME=/opt/acthome"
          - "ACT_DEBUG=Environment Response DBITrace Memory Timer"
        volumes:
            - "./:/opt/act"
            - "filestore:/opt/filestore"
            # Order is important as docker will override any mount point that
            # is less specific, directories override mounts and/or existing
            # files
            - "./conferences:/opt/acthome"
            - "./conferences/nlpw2018/wwwdocs:/opt/acthome/wwwdocs/nlpw2018"
            - "./templates:/opt/acthome/templates"
            - "./etc/act.ini:/opt/acthome/conf/act.ini"
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    database:
        image: "postgres:11"
        ports:
            - "5432:5432"
        networks:
            - "default"
        environment:
            - "POSTGRES_USER=act"
            - "POSTGRES_PASSWORD=act123"
            - "POSTGRES_DB=act"
        volumes:
            - "dbdata:/var/lib/postgresql/data"
            - "./db:/opt/act/db"
            - "./db/initial:/docker-entrypoint-initdb.d"
            - "./db/template.sql:/docker-entrypoint-initdb.d/00_init_db.sql"
            - "./db/template-wiki.sql:/docker-entrypoint-initdb.d/01_init_wiki_db.sql"
volumes:
    dbdata:
    filestore:
networks:
    default:
